// Complete list of NIFTY 50 stocks
const NIFTY_50 = [
  { symbol: 'RELIANCE.NS',   name: 'Reliance Industries',   sector: 'Energy', website: 'https://www.ril.com' },
  { symbol: 'TCS.NS',        name: 'Tata Consultancy Services', sector: 'IT', website: 'https://www.tcs.com' },
  { symbol: 'HDFCBANK.NS',   name: 'HDFC Bank',             sector: 'Banking', website: 'https://www.hdfcbank.com' },
  { symbol: 'INFY.NS',       name: 'Infosys',               sector: 'IT', website: 'https://www.infosys.com' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever',    sector: 'FMCG', website: 'https://www.hul.co.in' },
  { symbol: 'ICICIBANK.NS',  name: 'ICICI Bank',            sector: 'Banking', website: 'https://www.icicibank.com' },
  { symbol: 'KOTAKBANK.NS',  name: 'Kotak Mahindra Bank',   sector: 'Banking', website: 'https://www.kotak.com' },
  { symbol: 'SBIN.NS',       name: 'State Bank of India',   sector: 'Banking', website: 'https://www.sbi.co.in' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance',         sector: 'Finance', website: 'https://www.bajajfinserv.in/finance' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel',         sector: 'Telecom', website: 'https://www.airtel.in' },
  { symbol: 'WIPRO.NS',      name: 'Wipro',                 sector: 'IT', website: 'https://www.wipro.com' },
  { symbol: 'LT.NS',         name: 'Larsen & Toubro',       sector: 'Infrastructure', website: 'https://www.larsentoubro.com' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints',          sector: 'Consumer', website: 'https://www.asianpaints.com' },
  { symbol: 'HCLTECH.NS',    name: 'HCL Technologies',      sector: 'IT', website: 'https://www.hcltech.com' },
  { symbol: 'AXISBANK.NS',   name: 'Axis Bank',             sector: 'Banking', website: 'https://www.axisbank.com' },
  { symbol: 'MARUTI.NS',     name: 'Maruti Suzuki',         sector: 'Auto', website: 'https://www.marutisuzuki.com' },
  { symbol: 'SUNPHARMA.NS',  name: 'Sun Pharmaceutical',    sector: 'Pharma', website: 'https://www.sunpharma.com' },
  { symbol: 'TITAN.NS',      name: 'Titan Company',         sector: 'Consumer', website: 'https://www.titancompany.in' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement',      sector: 'Cement', website: 'https://www.ultratechcement.com' },
  { symbol: 'ONGC.NS',       name: 'ONGC',                  sector: 'Energy', website: 'https://www.ongcindia.com' },
  { symbol: 'NESTLEIND.NS',  name: 'Nestle India',          sector: 'FMCG', website: 'https://www.nestle.in' },
  { symbol: 'POWERGRID.NS',  name: 'Power Grid Corp',       sector: 'Utilities', website: 'https://www.powergrid.in' },
  { symbol: 'NTPC.NS',       name: 'NTPC',                  sector: 'Utilities', website: 'https://www.ntpc.co.in' },
  { symbol: 'M&M.NS',        name: 'Mahindra & Mahindra',   sector: 'Auto', website: 'https://www.mahindra.com' },
  { symbol: 'TECHM.NS',      name: 'Tech Mahindra',         sector: 'IT', website: 'https://www.techmahindra.com' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv',         sector: 'Finance', website: 'https://www.bajajfinserv.in' },
  { symbol: 'DRREDDY.NS',    name: "Dr. Reddy's Labs",      sector: 'Pharma', website: 'https://www.drreddys.com' },
  { symbol: 'CIPLA.NS',      name: 'Cipla',                 sector: 'Pharma', website: 'https://www.cipla.com' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors',           sector: 'Auto', website: 'https://www.tatamotors.com' },
  { symbol: 'COALINDIA.NS',  name: 'Coal India',            sector: 'Mining', website: 'https://www.coalindia.in' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank',         sector: 'Banking', website: 'https://www.indusind.com' },
  { symbol: 'EICHERMOT.NS',  name: 'Eicher Motors',         sector: 'Auto', website: 'https://www.eicher.in' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp',         sector: 'Auto', website: 'https://www.heromotocorp.com' },
  { symbol: 'GRASIM.NS',     name: 'Grasim Industries',     sector: 'Diversified', website: 'https://www.grasim.com' },
  { symbol: 'DIVISLAB.NS',   name: "Divi's Laboratories",   sector: 'Pharma', website: 'https://www.divislabs.com' },
  { symbol: 'HINDALCO.NS',   name: 'Hindalco Industries',   sector: 'Metals', website: 'https://www.hindalco.com' },
  { symbol: 'JSWSTEEL.NS',   name: 'JSW Steel',             sector: 'Metals', website: 'https://www.jsw.in/steel' },
  { symbol: 'TATASTEEL.NS',  name: 'Tata Steel',            sector: 'Metals', website: 'https://www.tatasteel.com' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports',           sector: 'Infrastructure', website: 'https://www.adaniports.com' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products',sector: 'FMCG', website: 'https://www.tataconsumer.com' },
  { symbol: 'BRITANNIA.NS',  name: 'Britannia Industries',  sector: 'FMCG', website: 'https://www.britannia.co.in' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals',      sector: 'Healthcare', website: 'https://www.apollohospitals.com' },
  { symbol: 'SBILIFE.NS',    name: 'SBI Life Insurance',    sector: 'Insurance', website: 'https://www.sbilife.co.in' },
  { symbol: 'HDFCLIFE.NS',   name: 'HDFC Life Insurance',   sector: 'Insurance', website: 'https://www.hdfclife.com' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto',            sector: 'Auto', website: 'https://www.bajajauto.com' },
  { symbol: 'UPL.NS',        name: 'UPL',                   sector: 'Chemicals', website: 'https://www.upl-ltd.com' },
  { symbol: 'SHREECEM.NS',   name: 'Shree Cement',          sector: 'Cement', website: 'https://www.shreecement.com' },
  { symbol: 'BPCL.NS',       name: 'BPCL',                  sector: 'Energy', website: 'https://www.bharatpetroleum.in' },
  { symbol: 'IOC.NS',        name: 'Indian Oil Corporation', sector: 'Energy', website: 'https://www.iocl.com' },
  { symbol: '^NSEI',         name: 'NIFTY 50 Index',        sector: 'Index', website: 'https://www.nseindia.com' },
];

module.exports = NIFTY_50;
