// Complete list of NIFTY 50 stocks
const NIFTY_50 = [
  { symbol: 'RELIANCE.NS',   name: 'Reliance Industries',   sector: 'Energy' },
  { symbol: 'TCS.NS',        name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK.NS',   name: 'HDFC Bank',             sector: 'Banking' },
  { symbol: 'INFY.NS',       name: 'Infosys',               sector: 'IT' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever',    sector: 'FMCG' },
  { symbol: 'ICICIBANK.NS',  name: 'ICICI Bank',            sector: 'Banking' },
  { symbol: 'KOTAKBANK.NS',  name: 'Kotak Mahindra Bank',   sector: 'Banking' },
  { symbol: 'SBIN.NS',       name: 'State Bank of India',   sector: 'Banking' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance',         sector: 'Finance' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel',         sector: 'Telecom' },
  { symbol: 'WIPRO.NS',      name: 'Wipro',                 sector: 'IT' },
  { symbol: 'LT.NS',         name: 'Larsen & Toubro',       sector: 'Infrastructure' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints',          sector: 'Consumer' },
  { symbol: 'HCLTECH.NS',    name: 'HCL Technologies',      sector: 'IT' },
  { symbol: 'AXISBANK.NS',   name: 'Axis Bank',             sector: 'Banking' },
  { symbol: 'MARUTI.NS',     name: 'Maruti Suzuki',         sector: 'Auto' },
  { symbol: 'SUNPHARMA.NS',  name: 'Sun Pharmaceutical',    sector: 'Pharma' },
  { symbol: 'TITAN.NS',      name: 'Titan Company',         sector: 'Consumer' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement',      sector: 'Cement' },
  { symbol: 'ONGC.NS',       name: 'ONGC',                  sector: 'Energy' },
  { symbol: 'NESTLEIND.NS',  name: 'Nestle India',          sector: 'FMCG' },
  { symbol: 'POWERGRID.NS',  name: 'Power Grid Corp',       sector: 'Utilities' },
  { symbol: 'NTPC.NS',       name: 'NTPC',                  sector: 'Utilities' },
  { symbol: 'M&M.NS',        name: 'Mahindra & Mahindra',   sector: 'Auto' },
  { symbol: 'TECHM.NS',      name: 'Tech Mahindra',         sector: 'IT' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv',         sector: 'Finance' },
  { symbol: 'DRREDDY.NS',    name: "Dr. Reddy's Labs",      sector: 'Pharma' },
  { symbol: 'CIPLA.NS',      name: 'Cipla',                 sector: 'Pharma' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors',           sector: 'Auto' },
  { symbol: 'COALINDIA.NS',  name: 'Coal India',            sector: 'Mining' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank',         sector: 'Banking' },
  { symbol: 'EICHERMOT.NS',  name: 'Eicher Motors',         sector: 'Auto' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp',         sector: 'Auto' },
  { symbol: 'GRASIM.NS',     name: 'Grasim Industries',     sector: 'Diversified' },
  { symbol: 'DIVISLAB.NS',   name: "Divi's Laboratories",   sector: 'Pharma' },
  { symbol: 'HINDALCO.NS',   name: 'Hindalco Industries',   sector: 'Metals' },
  { symbol: 'JSWSTEEL.NS',   name: 'JSW Steel',             sector: 'Metals' },
  { symbol: 'TATASTEEL.NS',  name: 'Tata Steel',            sector: 'Metals' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports',           sector: 'Infrastructure' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products',sector: 'FMCG' },
  { symbol: 'BRITANNIA.NS',  name: 'Britannia Industries',  sector: 'FMCG' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals',      sector: 'Healthcare' },
  { symbol: 'SBILIFE.NS',    name: 'SBI Life Insurance',    sector: 'Insurance' },
  { symbol: 'HDFCLIFE.NS',   name: 'HDFC Life Insurance',   sector: 'Insurance' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto',            sector: 'Auto' },
  { symbol: 'UPL.NS',        name: 'UPL',                   sector: 'Chemicals' },
  { symbol: 'SHREECEM.NS',   name: 'Shree Cement',          sector: 'Cement' },
  { symbol: 'BPCL.NS',       name: 'BPCL',                  sector: 'Energy' },
  { symbol: 'IOC.NS',        name: 'Indian Oil Corporation', sector: 'Energy' },
  { symbol: '^NSEI',         name: 'NIFTY 50 Index',        sector: 'Index' },
];

module.exports = NIFTY_50;
